DELETE FROM test.Poll
DELETE FROM test.Device
DELETE FROM test.UserAccount
INSERT INTO USERACCOUNT(ID, USERNAME, EMAIL, PASSWORD, ADMIN) values (2001, 'olanordmann', 'olanordmann@norge.no', 'norge', 0)
INSERT INTO USERACCOUNT(ID, USERNAME, EMAIL, PASSWORD, ADMIN) values (2002, 'andsim', 'andsim@uib.no', '1234', 0)
INSERT INTO USERACCOUNT(ID, USERNAME, EMAIL, PASSWORD, ADMIN) values (2003, 'rektor', 'rektor@uib.no', 'passord', 1)
INSERT INTO DEVICE(ID, YESVOTE, NOVOTE) values (2001, 16, 4)
INSERT INTO DEVICE(ID, YESVOTE, NOVOTE) values (2002, 7, 13)
INSERT INTO DEVICE(ID, YESVOTE, NOVOTE) values (2003, 2, 5)
INSERT INTO POLL(ID, QUESTION, YESVOTE, NOVOTE, ISPUBLIC, CODE, DURATION) values (1000, 'Er dette en test', 53, 3, 1, '1234', 25)